# Generated by Django 5.0 on 2024-08-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_mobile_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
